# Incremental loading: deep dive

In [70]:
!uv add pandas dlt[workspace]
import dlt
import duckdb

Resolved 120 packages in 40.83s
   Building edp-learning @ file:///workspaces/edp-learning
   Building edp-learning @ file:///workspaces/edp-learning
   Building edp-learning @ file:///workspaces/edp-learning
   Building edp-learning @ file:///workspaces/edp-learning
⠸ Preparing packages... (0/40)
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
referencing          ------------------------------     0 B/26.14 KiB
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
referencing          ------------------------------     0 B/26.14 KiB
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
referencing          ------------------------------     0 B/26.14 KiB
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
sse-starlette        ------------------------------     0 B/11.49 KiB
referencing          ------------------------------     0 B/26.14 KiB
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
sse-starlette        ------------------------------     0 B/11.49 KiB
referencing          ------------------------------     0 B/26.14 KiB
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
sse-starlette        ------------------------------     0 B/11.49 KiB
referencing          ------------------------------     0 B/26.14 KiB
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
sse-starlette        ------------------------------     0 B/11.49 KiB
referencing          ------------------------------     0 B/26.14 KiB
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
httpx-sse            ------------------------------     0 B/8.75 KiB
sse-starlette        ------------------------------     0 B/11.49 KiB
referencing          ------------------------------     0 B/26.14 KiB
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
httpx-sse            ------------------------------     0 B/8.75 KiB
sse-starlette        ------------------------------     0 B/11.49 KiB
referencing          ------------------------------     0 B/26.14 KiB
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
httpx-sse            ------------------------------     0 B/8.75 KiB
sse-starlette        ------------------------------     0 B/11.49 KiB
referencing          ------------------------------     0 B/26.14 KiB
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
httpx-sse            ------------------------------     0 B/8.75 KiB
sse-starlette        ------------------------------     0 B/11.49 KiB
referencing          ------------------------------     0 B/26.14 KiB
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
httpx-sse            ------------------------------     0 B/8.75 KiB
sse-starlette        ------------------------------     0 B/11.49 KiB
referencing          ------------------------------     0 B/26.14 KiB
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
httpx-sse            ------------------------------     0 B/8.75 KiB
sse-starlette        ------------------------------     0 B/11.49 KiB
referencing          ------------------------------     0 B/26.14 KiB
toolz                ------------------------------     0 B/56.73 KiB
   Building edp-learning @ file:///workspaces/edp-learning.03 KiB
⠸ Preparing packages... (0/40)
httpx-sse            ------------------------------     0 B/8.75 KiB
sse-starlette        ------------------------------     0 B/11.49 KiB
referencing          ------------------------------     0 B/26.14 KiB
toolz                ------------------------------     0 B/56.73 KiB
   Building edp-learning @ file:///workspaces/edp-learning66.03 KiB
⠸ Preparing packages... (0/40)
httpx-sse            ------------------------------     0 B/8.75 KiB
sse-starlette        ------------------------------     0 B/11.49 KiB
referencing          ------------------------------ 14.88 KiB/26.14 KiB
toolz                ------------------------------     0 B/56.73 KiB
   Building edp-learning @ file:///workspaces/edp-learning66.03 KiB
⠸ Preparing packages... (0/40)
httpx-sse            ------------------------------     0 B/8.75 KiB
sse-starlette        ------------------------------ 9.46 KiB/11.49 KiB
referencing          ------------------------------ 14.88 KiB/26.14 KiB
toolz                ------------------------------     0 B/56.73 KiB
   Building edp-learning @ file:///workspaces/edp-learning66.03 KiB
⠸ Preparing packages... (0/40)
httpx-sse            ------------------------------     0 B/8.75 KiB
sse-starlette        ------------------------------ 9.46 KiB/11.49 KiB
referencing          ------------------------------ 14.88 KiB/26.14 KiB
toolz                ------------------------------     0 B/56.73 KiB
   Building edp-learning @ file:///workspaces/edp-learning66.03 KiB
⠸ Preparing packages... (0/40)
httpx-sse            ------------------------------     0 B/8.75 KiB
sse-starlette        ------------------------------ 9.46 KiB/11.49 KiB
referencing          ------------------------------ 14.88 KiB/26.14 KiB
toolz                ------------------------------     0 B/56.73 KiB
   Building edp-learning @ file:///workspaces/edp-learning66.03 KiB
⠸ Preparing packages... (0/40)
httpx-sse            ------------------------------     0 B/8.75 KiB
sse-starlette        ------------------------------ 9.46 KiB/11.49 KiB
referencing          ------------------------------ 14.88 KiB/26.14 KiB
toolz                ------------------------------     0 B/56.73 KiB
   Building edp-learning @ file:///workspaces/edp-learning66.03 KiB
⠸ Preparing packages... (0/40)
httpx-sse                 ------------------------------     0 B/8.75 KiB
parsy                     ------------------------------     0 B/9.31 KiB
sse-starlette             ------------------------------ 9.46 KiB/11.49 KiB
typing-inspection         ------------------------------     0 B/14.27 KiB
itsdangerous              ------------------------------     0 B/15.85 KiB
jsonschema-specifications ------------------------------     0 B/18.00 KiB
python-dotenv             ------------------------------     0 B/20.73 KiB
pyjwt                     ------------------------------     0 B/22.46 KiB
python-multipart          ------------------------------     0 B/23.97 KiB
referencing               ------------------------------ 14.88 KiB/26.14 KiB
h11                       ------------------------------     0 B/36.64 KiB
pydantic-settings         ------------------------------     0 B/50.66 KiB
toolz                     ------------------------------     0 B/56.73 KiB
attrs                     ------------------------------ 14.88 KiB/66.03 KiB
uvicorn                   ------------------------------     0 B/66.51 KiB
jsonschema                ------------------------------     0 B/87.93 KiB
anyio                     ------------------------------     0 B/110.71 KiB
pycparser                 ------------------------------     0 B/115.37 KiB
websockets                ------------------------------     0 B/178.25 KiB
rpds-py                   ------------------------------     0 B/384.84 KiB
docutils                  ------------------------------     0 B/618.20 KiB
   Building edp-learning @ file:///workspaces/edp-learningB/1.98 MiB
⠸ Preparing packages... (0/40)
atpublic                  ------------------------------     0 B/6.27 KiB
parsy                     ------------------------------     0 B/9.31 KiB
sse-starlette             ------------------------------ 9.46 KiB/11.49 KiB
annotated-types           ------------------------------     0 B/13.32 KiB
typing-inspection         ------------------------------     0 B/14.27 KiB
itsdangerous              ------------------------------     0 B/15.85 KiB
jsonschema-specifications ------------------------------     0 B/18.00 KiB
python-dotenv             ------------------------------     0 B/20.73 KiB
pyjwt                     ------------------------------     0 B/22.46 KiB
python-multipart          ------------------------------     0 B/23.97 KiB
referencing               ------------------------------ 14.88 KiB/26.14 KiB
pathspec                  ------------------------------     0 B/30.46 KiB
h11                       ------------------------------     0 B/36.64 KiB
pydantic-settings         ------------------------------     0 B/50.66 KiB
toolz                     ------------------------------     0 B/56.73 KiB
attrs                     ------------------------------ 14.88 KiB/66.03 KiB
uvicorn                   ------------------------------     0 B/66.51 KiB
httpx                     ------------------------------     0 B/71.79 KiB
starlette                 ------------------------------     0 B/72.30 KiB
httpcore                  ------------------------------     0 B/76.94 KiB
jsonschema                ------------------------------     0 B/87.93 KiB
   Building edp-learning @ file:///workspaces/edp-learningB/105.15 KiB
⠸ Preparing packages... (0/40)
atpublic                  ------------------------------     0 B/6.27 KiB
parsy                     ------------------------------     0 B/9.31 KiB
sse-starlette             ------------------------------ 9.46 KiB/11.49 KiB
annotated-types           ------------------------------     0 B/13.32 KiB
typing-inspection         ------------------------------     0 B/14.27 KiB
itsdangerous              ------------------------------     0 B/15.85 KiB
jsonschema-specifications ------------------------------     0 B/18.00 KiB
python-dotenv             ------------------------------     0 B/20.73 KiB
pyjwt                     ------------------------------     0 B/22.46 KiB
python-multipart          ------------------------------     0 B/23.97 KiB
referencing               ------------------------------ 14.88 KiB/26.14 KiB
pathspec                  ------------------------------     0 B/30.46 KiB
h11                       ------------------------------     0 B/36.64 KiB
pydantic-settings         ------------------------------ 11.59 KiB/50.66 KiB
toolz                     ------------------------------ 16.00 KiB/56.73 KiB
attrs                     ------------------------------ 14.88 KiB/66.03 KiB
uvicorn                   ------------------------------     0 B/66.51 KiB
httpx                     ------------------------------     0 B/71.79 KiB
starlette                 ------------------------------     0 B/72.30 KiB
httpcore                  ------------------------------     0 B/76.94 KiB
jsonschema                ------------------------------     0 B/87.93 KiB
   Building edp-learning @ file:///workspaces/edp-learningB/105.15 KiB
⠸ Preparing packages... (0/40)
atpublic                  ------------------------------     0 B/6.27 KiB
parsy                     ------------------------------     0 B/9.31 KiB
sse-starlette             ------------------------------ 9.46 KiB/11.49 KiB
annotated-types           ------------------------------     0 B/13.32 KiB
typing-inspection         ------------------------------ 14.27 KiB/14.27 KiB
itsdangerous              ------------------------------     0 B/15.85 KiB
jsonschema-specifications ------------------------------     0 B/18.00 KiB
python-dotenv             ------------------------------     0 B/20.73 KiB
pyjwt                     ------------------------------     0 B/22.46 KiB
python-multipart          ------------------------------ 14.87 KiB/23.97 KiB
referencing               ------------------------------ 14.88 KiB/26.14 KiB
pathspec                  ------------------------------     0 B/30.46 KiB
h11                       ------------------------------     0 B/36.64 KiB
pydantic-settings         ------------------------------ 11.59 KiB/50.66 KiB
toolz                     ------------------------------ 16.00 KiB/56.73 KiB
attrs                     ------------------------------ 14.88 KiB/66.03 KiB
uvicorn                   ------------------------------     0 B/66.51 KiB
httpx                     ------------------------------     0 B/71.79 KiB
starlette                 ------------------------------     0 B/72.30 KiB
httpcore                  ------------------------------     0 B/76.94 KiB
jsonschema                ------------------------------     0 B/87.93 KiB
   Building edp-learning @ file:///workspaces/edp-learningKiB/105.15 KiB
⠸ Preparing packages... (0/40)
atpublic                  ------------------------------     0 B/6.27 KiB
parsy                     ------------------------------     0 B/9.31 KiB
sse-starlette             ------------------------------ 9.46 KiB/11.49 KiB
annotated-types           ------------------------------     0 B/13.32 KiB
itsdangerous              ------------------------------     0 B/15.85 KiB
jsonschema-specifications ------------------------------     0 B/18.00 KiB
python-dotenv             ------------------------------     0 B/20.73 KiB
pyjwt                     ------------------------------     0 B/22.46 KiB
python-multipart          ------------------------------ 14.87 KiB/23.97 KiB
referencing               ------------------------------ 14.88 KiB/26.14 KiB
pathspec                  ------------------------------     0 B/30.46 KiB
h11                       ------------------------------     0 B/36.64 KiB
pydantic-settings         ------------------------------ 11.59 KiB/50.66 KiB
toolz                     ------------------------------ 16.00 KiB/56.73 KiB
attrs                     ------------------------------ 14.88 KiB/66.03 KiB
uvicorn                   ------------------------------     0 B/66.51 KiB
httpx                     ------------------------------     0 B/71.79 KiB
starlette                 ------------------------------     0 B/72.30 KiB
httpcore                  ------------------------------     0 B/76.94 KiB
jsonschema                ------------------------------     0 B/87.93 KiB
markdown                  ------------------------------ 14.85 KiB/105.15 KiB
   Building edp-learning @ file:///workspaces/edp-learningB/110.71 KiB
⠼ Preparing packages... (1/40)
parsy                     ------------------------------     0 B/9.31 KiB
sse-starlette             ------------------------------ 9.46 KiB/11.49 KiB
annotated-types           ------------------------------     0 B/13.32 KiB
itsdangerous              ------------------------------     0 B/15.85 KiB
jsonschema-specifications ------------------------------     0 B/18.00 KiB
python-dotenv             ------------------------------     0 B/20.73 KiB
pyjwt                     ------------------------------     0 B/22.46 KiB
python-multipart          ------------------------------ 14.87 KiB/23.97 KiB
referencing               ------------------------------ 14.88 KiB/26.14 KiB
pathspec                  ------------------------------     0 B/30.46 KiB
h11                       ------------------------------     0 B/36.64 KiB
pydantic-settings         ------------------------------ 11.59 KiB/50.66 KiB
toolz                     ------------------------------ 16.00 KiB/56.73 KiB
attrs                     ------------------------------ 14.88 KiB/66.03 KiB
uvicorn                   ------------------------------     0 B/66.51 KiB
httpx                     ------------------------------     0 B/71.79 KiB
starlette                 ------------------------------     0 B/72.30 KiB
httpcore                  ------------------------------ 2.11 KiB/76.94 KiB
jsonschema                ------------------------------     0 B/87.93 KiB
markdown                  ------------------------------ 14.85 KiB/105.15 KiB
anyio                     ------------------------------     0 B/110.71 KiB
   Building edp-learning @ file:///workspaces/edp-learningB/115.37 KiB
⠼ Preparing packages... (1/40)
parsy                     ------------------------------     0 B/9.31 KiB
annotated-types           ------------------------------     0 B/13.32 KiB
itsdangerous              ------------------------------     0 B/15.85 KiB
jsonschema-specifications ------------------------------     0 B/18.00 KiB
python-dotenv             ------------------------------     0 B/20.73 KiB
pyjwt                     ------------------------------     0 B/22.46 KiB
python-multipart          ------------------------------ 14.87 KiB/23.97 KiB
referencing               ------------------------------ 14.88 KiB/26.14 KiB
pathspec                  ------------------------------     0 B/30.46 KiB
h11                       ------------------------------     0 B/36.64 KiB
pydantic-settings         ------------------------------ 11.59 KiB/50.66 KiB
toolz                     ------------------------------ 16.00 KiB/56.73 KiB
attrs                     ------------------------------ 14.88 KiB/66.03 KiB
uvicorn                   ------------------------------     0 B/66.51 KiB
httpx                     ------------------------------     0 B/71.79 KiB
starlette                 ------------------------------     0 B/72.30 KiB
httpcore                  ------------------------------ 2.11 KiB/76.94 KiB
jsonschema                ------------------------------     0 B/87.93 KiB
markdown                  ------------------------------ 14.85 KiB/105.15 KiB
anyio                     ------------------------------     0 B/110.71 KiB
pycparser                 ------------------------------     0 B/115.37 KiB
   Building edp-learning @ file:///workspaces/edp-learningB/178.25 KiB
⠼ Preparing packages... (1/40)
parsy                     ------------------------------     0 B/9.31 KiB
annotated-types           ------------------------------     0 B/13.32 KiB
itsdangerous              ------------------------------     0 B/15.85 KiB
jsonschema-specifications ------------------------------     0 B/18.00 KiB
python-dotenv             ------------------------------     0 B/20.73 KiB
pyjwt                     ------------------------------     0 B/22.46 KiB
python-multipart          ------------------------------ 14.87 KiB/23.97 KiB
referencing               ------------------------------ 26.14 KiB/26.14 KiB
pathspec                  ------------------------------     0 B/30.46 KiB
h11                       ------------------------------     0 B/36.64 KiB
pydantic-settings         ------------------------------ 11.59 KiB/50.66 KiB
toolz                     ------------------------------ 16.00 KiB/56.73 KiB
attrs                     ------------------------------ 30.88 KiB/66.03 KiB
uvicorn                   ------------------------------     0 B/66.51 KiB
httpx                     ------------------------------     0 B/71.79 KiB
starlette                 ------------------------------     0 B/72.30 KiB
httpcore                  ------------------------------ 2.11 KiB/76.94 KiB
jsonschema                ------------------------------     0 B/87.93 KiB
markdown                  ------------------------------ 14.85 KiB/105.15 KiB
anyio                     ------------------------------     0 B/110.71 KiB
pycparser                 ------------------------------     0 B/115.37 KiB
   Building edp-learning @ file:///workspaces/edp-learningB/178.25 KiB
⠼ Preparing packages... (1/40)
parsy                     ------------------------------     0 B/9.31 KiB
annotated-types           ------------------------------     0 B/13.32 KiB
itsdangerous              ------------------------------ 15.85 KiB/15.85 KiB
jsonschema-specifications ------------------------------     0 B/18.00 KiB

## 1. Introduction

In this lesson, we will take a deep dive into how incremental loading works in `dlt`, and how you can customize it to fit your needs.

We will also learn:
- how to perform backfills
- how to handle late arriving data
- how to optimize incremental pipelines
- caveats of incremental loading in dlt
- how to debug common incremental loading issues

## 2. How incremental loading works in `dlt`

There are two main components that work together to enable incremental loading in `dlt`:

- Cursor configuration
- Pipeline state

We configure a cursor to let `dlt` know how to identify new or updated rows in the source data. `dlt` will then store the last seen cursor value in the pipeline state, and use it to filter the source data on subsequent runs.

Notably, the filtering is performed **after** the data is extracted from the source and any [mapping funcions](https://dlthub.com/docs/dlt-ecosystem/transformations/add-map), but **before** it is normalized and loaded into the destination.

### Cursor configuration

Cursor configuration consists of the following core components:

- Cursor column
- Cursor initial value
- Cursor end value (optional)

The latter two, combined with pipeline state, are used by `dlt` to determine the current cursor value at the start of each pipeline run.

For more information on how pipeline state is used in incremental loading, see the [Pipeline state](#pipeline-state) section below.

#### Cursor column

This is the column in the source data that `dlt` uses to determine which rows are new or updated since the last load. It's typically a timestamp column.

#### Cursor value

This is the value of the cursor column from the last successful load. `dlt` uses this value to filter the source data. We can manually specify the initial and end values for specific purposes.

#### Cursor initial value

This is the value that `dlt` uses for the cursor value on the first run of the pipeline. It is specified in the `dlt` configuration file (`config.toml`).

#### Cursor end value

This is used by `dlt` for backfills. Specifing this value tells `dlt` to **not** update the cursor value after the run, allowing you to re-extract data up to this value in subsequent runs.

### Pipeline state

This is a persistent storage that `dlt` uses to store the cursor value and other metadata about pipeline runs. It allows `dlt` to remember the state of each resource between pieline runs.

Below is a diagram showcasing how pipeline state is used during a pipeline run:

![dlt incremental loads - pipeline state](../assets/dlt_incremental_loads_pipeline_state.png)

Notably, on the first execution, the pipeline will use the specified `cursor_initial_value` to filter the data:

![dlt incremental loads - pipeline state - first run](../assets/dlt_incremental_loads_pipeline_state__first_run.png)

During the following executions, dlt will read the `last_value` value from state and set `cursor.start_value` to this value (note: yes, this means dlt can potentially re-fetch some of the data - this is why deduplication is performed by default).

### Cursor value types & timezones

## 3. Backfilling data

In [1]:
from datetime import datetime

def fake_api_get(
        endpoint: str,
        start_time: str,
        pipeline_execution_start: datetime,
        end_time: str | None = None,
        endpoint_params: dict | None = None,
    ):
    """Simulate an API returning some data."""
    if endpoint == "my_endpoint":
        data = [
            {"id": 1, "updated_at": "2025-03-03T01:00:00Z", "content": "1"},
            {"id": 2, "updated_at": "2025-03-03T02:00:00Z", "content": "2"},
            {"id": 3, "updated_at": "2025-03-03T03:00:00Z", "content": "3"},
            {"id": 6, "updated_at": "2025-03-03T06:00:00Z", "content": "6"},
            {"id": 7, "updated_at": "2025-03-03T07:00:00Z", "content": "7"},
            # Updates become available only after their _available_after.
            {"id": 1, "updated_at": "2025-03-03T08:00:00Z", "content": "1_updated", "_available_after": "2025-03-03T08:01:00Z"},
            {"id": 4, "updated_at": "2025-03-03T09:00:00Z", "content": "4", "_available_after": "2025-03-03T08:01:00Z"},
            {"id": 5, "updated_at": "2025-03-03T10:00:00Z", "content": "5", "_available_after": "2025-03-03T08:01:00Z"},
        ]

    start_time_dt = datetime.fromisoformat(start_time)
    end_time_dt = datetime.fromisoformat(end_time) if end_time else None

    out = []
    for record in data:
        updated_at_dt = datetime.fromisoformat(record["updated_at"])

        if updated_at_dt < start_time_dt:
            # Record outside of selected range.
            continue
        if end_time_dt and updated_at_dt > end_time_dt:
            # Record outside of selected range.
            continue
        if available_after := record.get("_available_after"):
            if pipeline_execution_start < datetime.fromisoformat(available_after):
                # Record simulated to not yet be available in the API.
                continue
        out.append({k: v for k, v in record.items() if not k.startswith("_")})
    return out

In [2]:
import dlt
import duckdb


@dlt.source
def my_api_source(
    endpoint: str,
    primary_key: str,
    cursor_column: str,
    cursor_initial_value: str,
    cursor_end_value: str | None = None,
    endpoint_params: dict | None = None,
):
    """An example dlt source with dynamically generated resources.

    Args:
        endpoint (str): The endpoint to fetch data from.
        primary_key (str): The primary key of the resulting table.
        cursor_column (str): The column to use as a cursor.
        cursor_initial_value (str): The initial value for the cursor.
        cursor_end_value (str | None, optional): The end value for the cursor. Defaults
            to None.
        endpoint_params (dict | None, optional): Any parameters to pass to the endpoint
            call.
    """
    def get_data(cursor: dlt.sources.incremental):
        """Retrieve data from the specified fake API endpoint.

        Args:
            cursor (dlt.sources.incremental): The dlt cursor object to use for filtering
                the data.
        """
        global is_second_run

        if not is_second_run:
            pipeline_start_time = datetime.fromisoformat("2025-03-03T04:01:00Z")
        else:
            pipeline_start_time = datetime.fromisoformat("2025-03-03T08:01:00Z")

        yield fake_api_get(
            endpoint=endpoint,
            start_time=cursor.start_value,
            end_time=cursor.end_value,
            pipeline_execution_start=pipeline_start_time,
            endpoint_params=endpoint_params,
        )

    # initial_value = datetime.fromisoformat(cursor_initial_value)
    # end_value = datetime.fromisoformat(cursor_end_value)

    # Since the input params to the cursor object are dynamic (can differ between
    # endpoints), we need to create the cursor and resource objects this way instead of
    # using the @dlt.resource decorator.
    return dlt.resource(get_data, name=endpoint, primary_key=primary_key)(
        cursor=dlt.sources.incremental(
            cursor_column,
            initial_value=cursor_initial_value,
            end_value=cursor_end_value
        ),
    )

pipeline = dlt.pipeline(
    "backfill_pipe",
    destination=dlt.destinations.duckdb(credentials=duckdb.connect(":memory:")),
)

my_resource = my_api_source(
    endpoint="my_endpoint",
    primary_key="id",
    cursor_column="updated_at",
    cursor_initial_value="2025-03-03T06:00:00Z"
)

is_second_run = False

# Run the pipeline twice
pipeline.run(my_resource, write_disposition="merge")
pipeline.dataset().table("my_endpoint").df().sort_values("content")
# is_second_run = True  # Update flag for second run
# load_info = pipeline.run(my_resource, write_disposition="merge")
# pipeline.dataset().table("events").df()

   id                updated_at content        _dlt_load_id         _dlt_id
0   6 2025-03-03 06:00:00+00:00       6  1765372915.8847528  EJRAFnRkpN2QSQ
1   7 2025-03-03 07:00:00+00:00       7  1765372915.8847528  pilgUkRW8vcvhQ

Let's inspect the pipeline's state:

In [3]:
print(pipeline.state["sources"]["my_api_source"]["resources"]["my_endpoint"]["incremental"]["updated_at"])

{'initial_value': '2025-03-03T06:00:00Z', 'last_value': '2025-03-03T07:00:00Z', 'unique_hashes': ['+ZB5qOrG8FH6xOYrF/a8']}

As you can see, dlt set `last_value` to the last seen value in the cursor column (in our case, the `updated_at` field). This means that our incremental load worked as expected - despite there being more data available in the endpoint, we only loaded data updated since our chosen checkpoint.

Now, let's imagine that istead of only loading data since some recent checkpoint, we  wanted to make a large initial load to "catch up" with the data before enabling incremental loads.

In such case, we can execute a backfill by specifying the end value for the cursor:

In [4]:
# Clean up pipeline state so we can simulate a different scenario.
pipeline.drop()

my_resource = my_api_source(
    endpoint="my_endpoint",
    primary_key="id",
    cursor_column="updated_at",
    cursor_initial_value="2025-03-03T00:00:00Z",
    cursor_end_value="2025-03-03T04:00:00Z",
)
pipeline.run(my_resource, write_disposition="replace")  # Notice we changed this from "merge".
pipeline.dataset().table("my_endpoint").df().sort_values("content")

   id                updated_at content        _dlt_load_id         _dlt_id
0   1 2025-03-03 01:00:00+00:00       1  1765372919.4170682  2Sw9wtSlM7MwTg
1   2 2025-03-03 02:00:00+00:00       2  1765372919.4170682  16GkzSMsUB7D0Q
2   3 2025-03-03 03:00:00+00:00       3  1765372919.4170682  5R84nMeGqn4qHg

Let's inspect the pipeline's state again:

In [5]:
print(pipeline.state["sources"]["my_api_source"]["resources"])

{}

Notice how no state is tracked for our resource! This is because in dlt, backfills **do not modify resource state**.

Instead, on our next incremental run, we need to set `initial_value` to the end value of the backfill:

In [6]:
my_resource = my_api_source(
    endpoint="my_endpoint",
    primary_key="id",
    cursor_column="updated_at",
    cursor_initial_value="2025-03-03T04:00:00Z"  # Now set to 4AM (previous incremental example used 6AM).
)
pipeline.run(my_resource, write_disposition="merge")  # Change back to "merge".
pipeline.dataset().table("my_endpoint").df().sort_values("content")

   id                updated_at content        _dlt_load_id         _dlt_id
0   1 2025-03-03 01:00:00+00:00       1  1765372919.4170682  2Sw9wtSlM7MwTg
1   2 2025-03-03 02:00:00+00:00       2  1765372919.4170682  16GkzSMsUB7D0Q
2   3 2025-03-03 03:00:00+00:00       3  1765372919.4170682  5R84nMeGqn4qHg
3   6 2025-03-03 06:00:00+00:00       6  1765372924.3151872  kFcj9XZnSGKPsg
4   7 2025-03-03 07:00:00+00:00       7  1765372924.3151872  CzNAdRYGQGjMQA

Let's double check that state is now created and tracked correctly:

In [7]:
print(pipeline.state["sources"]["my_api_source"]["resources"]["my_endpoint"]["incremental"]["updated_at"])

{'initial_value': '2025-03-03T04:00:00Z', 'last_value': '2025-03-03T07:00:00Z', 'unique_hashes': ['+ZB5qOrG8FH6xOYrF/a8']}

Finally, let's simulate a second incremental run:

In [8]:
is_second_run = True
pipeline.run(my_resource, write_disposition="merge")  # Change back to "merge".
pipeline.dataset().table("my_endpoint").df().sort_values("content")

   id                updated_at    content        _dlt_load_id         _dlt_id
5   1 2025-03-03 08:00:00+00:00  1_updated  1765372929.9534838  K9LLtMvKwO+R7A
0   2 2025-03-03 02:00:00+00:00          2  1765372919.4170682  16GkzSMsUB7D0Q
1   3 2025-03-03 03:00:00+00:00          3  1765372919.4170682  5R84nMeGqn4qHg
4   4 2025-03-03 09:00:00+00:00          4  1765372929.9534838  Ibru1JP0WxlPXQ
6   5 2025-03-03 10:00:00+00:00          5  1765372929.9534838  v/rGA1HqwF8+3Q
2   6 2025-03-03 06:00:00+00:00          6  1765372924.3151872  kFcj9XZnSGKPsg
3   7 2025-03-03 07:00:00+00:00          7  1765372924.3151872  CzNAdRYGQGjMQA

In [9]:
load_id = list(pipeline.last_trace.last_extract_info.metrics.keys())[0]
extracted_rows = pipeline.last_trace.last_extract_info.metrics[load_id][0]["table_metrics"]["my_endpoint"].items_count
extracted_rows

3

As expected, newly updated records have been loaded. To make sure, let's verify that only the 3 new/updated records were in fact processed in this pipeline run:

In [10]:
!dlt pipeline backfill_pipe show

        Running dlt_dashboard.py ⚡

        ➜  URL: http://localhost:2718

        Are you sure you want to quit? (y/n): ^C

## 4. Handling late arriving data

Sometimes, datasets don't have a field indicating modification date. However, in some cases, you might still be able to implement incremental loading -- for example, when you have a creation date field, and you know records are only modified for some specified time after creation. In such case, you can use dlt's lag/attribution window feature.

In the example below, we have events generated each hour, but they can still be updated for some time after creation. Let's pretend the second event is modified just one minute after the initial data ingestion finishes. Thankfully, since we configured a one-hour lag, dlt re-fetches all events created at and after 2023-03-03T02:00:00Z, and the event is correctly updated.

In [ ]:
@dlt.resource(name="events", primary_key="id", write_disposition="merge")
def events_resource(
    _=dlt.sources.incremental("created_at", lag=60*60)  # 1-hour lag.
):
    global is_second_run

    # First pipeline run is executed at 3:01 AM and fetches events created/updated up to
    # 4 AM.
    initial_entries = [
        {"id": 1, "created_at": "2023-03-03T01:00:00Z", "event": "1_already_updated"},
        {"id": 2, "created_at": "2023-03-03T02:00:00Z", "event": "2"},
        {"id": 3, "created_at": "2023-03-03T03:00:00Z", "event": "3"},
    ]

    # Second pipeline run is executed at 5:01 AM. We query API to return records
    # created at/after 2023-03-03T02:00:00Z.
    second_run_events = [
        {"id": 2, "created_at": "2023-03-03T02:00:00Z", "event": "2_updated"},  # late-arriving update.
        {"id": 4, "created_at": "2023-03-03T04:00:00Z", "event": "4"},
        {"id": 5, "created_at": "2023-03-03T05:00:00Z", "event": "5"},
    ]

    yield from second_run_events if is_second_run else initial_entries


pipeline = dlt.pipeline(
    "lag_pipe",
    destination=dlt.destinations.duckdb(credentials=duckdb.connect(":memory:")),
)

is_second_run = False

# Run the pipeline twice
pipeline.run(events_resource)
pipeline.dataset().table("events").df()
is_second_run = True  # Update flag for second run
load_info = pipeline.run(events_resource)
pipeline.dataset().table("events").df()

,id,created_at,event,_dlt_load_id,_dlt_id
0,3,2023-03-03 03:00:00+00:00,3,1764851825.282592,tY0hSzzgCt2JmQ
1,1,2023-03-03 01:00:00+00:00,1_already_updated,1764851825.282592,3BXjdrGhNcNvPQ
2,5,2023-03-03 05:00:00+00:00,5,1764851825.8009284,lf0kLSdfFj0r5g
3,2,2023-03-03 02:00:00+00:00,2_updated,1764851825.8009284,iAx4S5jNrLu9ZQ
4,4,2023-03-03 04:00:00+00:00,4,1764851825.8009284,J/8O+YjwKd25/g

Feel free to decrese the `lag` to eg. 30 minutes and re-run the pipeline to see that the second event is **not** updated without the correct `lag` value.

## 5. Optimizing

## 6. Caveats

6.1 Sparse cursor values

6.2 Handling different dataset and API endpoint cursor columns

Quite often, an API will return a column such as `updated_at`, but the endpoint will not allow us to filter by this field. For example, the endpoint will expose a different `start_at` paramerter.

Fortunately, with `dlt`, you can easily handle such cases. Here is an example:

```python
import dlt
from datetime import datetime
from dlt.sources.helpers import requests

@dlt.source
def my_api_source():
    @dlt.resource(primary_key="id")
    def my_endpoint(
        cursor: dlt.sources.incremental = dlt.sources.incremental(
            "updated_at",
            initial_value=datetime.fromisoformat("2025-01-01T00:00:00Z")
        )
    ):
        return requests.get("my_endpoint", params={"start_at": cursor.start_value.isoformat()})
```

Sometimes, there is a discrepancy between the `start_at` and `updated_at` fields, eg. there is some time offset between them. In such cases, you can use the `lag` feature to cover these descrepancies by re-fetching some time window of data. The `cursor.start_value` will be automatically adjusted by the `lag` value, so no changes to the code are needed, besides specifying the `lag` param.

### 7.1 Incorrect cursor column name

#### Specifying normalized name

When

Remember that incremental filtering is applied **after** the data is extracted and any mapping functions are applied, but **before** normalization and loading. Due to this, we need to use the non-normalized column name when specifying the cursor column:

Resource:

```json
{"MyColumn": "value"}
```

Incorrect incremental configuration:
```python
dlt.sources.incremental("my_column")
```

Correct incremental configuration:
```python
dlt.sources.incremental("MyColumn")
```


#### Not escaping special characters

A common issue is when the resource retrieves data in the following format:

```json
{"My Column": "value"}
```

And then we try to specify the cursor column as:

```python
dlt.sources.incremental("My Column")
```

However, internally, `dlt` uses JSONPath to select the cursor value using our specified column name as part of the path. So, in this case, we need to escape the special characters (space) in the column name by wrapping it in `['...']`:

```python
dlt.sources.incremental("['My Column']")
```